### ISSUE TITLE
Option to run the pretty printer with no maximum width set

### ISSUE THREAD

**Issue by brendanzab** [Marwes/pretty.rs#38]
It would be nice to run the pretty printer with an unbounded width. At the moment I have to pick an arbitrary default - say, when implementing `fmt::Display`, or when not in a tty mode where I can get a terminal width.

**Comment by Marwes** [comment]
If you just set the width to `usize::MAX` you will get an essentially unbounded width. Not the most elegant but it works.

**Comment by JayKickliter** [comment]
@brendanzab should this also be closed?

**Comment by Marwes** [comment]
Yeah, might as well, I don't think there is a case where `usize::MAX` would fail.

**Comment by brendanzab** [comment]
Possibly - I think I might make a new bug - using `usize::MAX` seems to result in every line being broken, rather than an unbounded-ish line length.
