### ISSUE TITLE
unable to run trees example

### ISSUE THREAD

**Issue by vilterp** [Marwes/pretty.rs#41]
Hi, Rust newbie here — neither `cargo run` (as in the readme) or `cargo run --example trees` runs the trees example for me:

```
$ cargo run
error: a bin target must be available for `cargo run`
$ cargo run --example trees
error: no example target named `trees`
```

However, the colored example does work:

```
$ cargo run --example colored --features="termcolor"
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/colored`
red blue bold intense
```

Lib version dad1ca39df5abd203ada7d7d459158ba196711c8; cargo version 1.26.0.

Thanks! Great library.

**Comment by Marwes** [comment]
Thanks for reporting! Fixed in https://github.com/Marwes/pretty.rs/commit/c28463d07fc25853dae852c5ea7f1eea6f098a5e

**Comment by vilterp** [comment]
Holy moly, that was fast. Works great now! Thanks.
