### ISSUE TITLE
Algorithm Unwilling to Collapse Output to Single Line

### ISSUE THREAD

**Issue by eignnx** [Marwes/pretty.rs#48]
Version: 0.5.3-alpha.0

Hi, I'm not sure if this is a bug, or my misunderstanding of a feature.

I've been having trouble getting the algorithm to choose to print things on one line when it has enough space and when a `Doc::newline()` is in the builder. I tried getting the [`trees` example](https://github.com/Marwes/pretty.rs/blob/master/examples/trees.rs) to print one one line by increasing the [render width from 70](https://github.com/Marwes/pretty.rs/blob/7fb895eff160b8bfd6d28efb19bf24f0b9326109/examples/trees.rs#L103) to 1000, but it always chooses to spread things out over multiple lines.

In this example:
```rust
Doc::text("1234567890")
    .append(Doc::newline())
    .append(Doc::text("1234567890"))
    .group()
```
Shouldn't the `group` operation (conceptually) return a "set" of two possible layouts, one with the newline and one without it? My understanding was that the algorithm has the freedom to delete newlines if it needs to. But it seems to always keep the newline in the output.

Am I misunderstanding how `Doc::newline()` is supposed to work?

Thanks for your time

**Comment by Marwes** [comment]
You want [space](https://docs.rs/pretty/0.5.2/pretty/trait.DocAllocator.html#method.space). `newline` is always a new line

**Comment by eignnx** [comment]
Oh ok, thanks! In 0.5.2, is there a way to print either a newline or nothing? I've noticed that in the alpha version work is being done on `Doc.flat_alt`. Should I be using that?

**Comment by Marwes** [comment]
I don't believe that is possible on 0.5 . I want to get a `Union` document into the next version as well but it needs some more invasive changes to the internals that I haven't gotten around to. If I don't get around to it soon-ish I will make a release with what exists.

**Comment by eignnx** [comment]
Currently I'm just referencing the git repo for 0.5.3-alpha.0 and using `flat_alt`. Everything seems to be working :man_shrugging:. I'd love it if the current features (or even just the `flat_alt` feature) could be released onto crates.io, but no rush :smile:

**Comment by eignnx** [comment]
Thanks so much!
