### ISSUE TITLE
Help converting RefCell<T> to Doc

### ISSUE THREAD

**Issue by sgpthomas** [Marwes/pretty.rs#61]
Hello, I have a trait called `PrettyPrint` for converting types into `RcDoc`.
```rust
pub trait PrettyPrint {
  fn pretty(&self) -> RcDoc;
}
```

Is it possible to implement this type for `RefCell<T: PrettyPrint>`?

```rust
impl<T: PrettyPrint> PrettyPrint for RefCell<T> {
    fn pretty(&self) -> RcDoc {
        self.borrow().pretty()
    }
}
```

I want something that looks like this but the reference returned from `self.borrow()` is a locally allocated value and thus has a shorter lifetime then `&self` and so this function doesn't compile. What is the proper way to implement this function?

**Comment by Marwes** [comment]
You will need to make sure that the returned `RcDoc` does not borrow from `self`.

```
pub trait PrettyPrint {
  fn pretty(&self) -> RcDoc<'static>;
}
```

Might do the trick
