### ISSUE TITLE
Having multiple lines be stuck together

### ISSUE THREAD

**Issue by TheNeikos** [Marwes/pretty.rs#78]
I would like to use `pretty` to create structured error output. One use-case is that I'd like to underline errors in lines.

For example:

```
     this.do_stuff();
          ~~~~~~~~
              ^ `do_stuff` could not be found on `this`
```

Now, I understand if that might not be 100% what this library is for, but I feel like it could be supported? 

The whole block can be seen as a single 'line' that does its own re-sizing internally.

A degenerate case, with a column width of 5 for the line+squigglies

```
this.
do_st
~~~~~
uff()
~~
;
  ^ `do_stuff` could not be found on `this`
```

Is this maybe already possible? (I looked really hard in the docs, but not all methods are documented, so I might have missed it)

**Comment by Marwes** [comment]
> A degenerate case, with a column width of 5 for the line+squigglies

This example doesn't really work in the document model as it will only do a best effort to keep the output inside the maximum width and doesn't break up individual text segments (though I guess you might be able to do text segments that are one letter each, maybe).

That said you might be able to do something using annotations. If you add a custom annotations called underline, mark the section you want underlined with it then with a custom document formatter you might be able write the underlining there.

I don't think it is something that would be explicitly supported in pretty though as I can't really see a general way of imlpementing it.

**Comment by TheNeikos** [comment]
Alright, thank you for the quick and clear answer! I had to try and see if it could fit somehow at least.
